<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
<!ELEMENT students (students)+>
<!ELEMENT student (id , first-name , last-name)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
]>
<students>
    <student>
        <id>10001</id>
        <first-name>Name</first-name>
        <last-name>Surname</last-name>
    </student>
    <student>
        <id>10002</id>
        <first-name>Name2</first-name>
        <last-name>Surname2</last-name>
    </student>
    <student>
        <id>10003</id>
        <first-name>Name3</first-name>
        <last-name>Surname3</last-name>
    </student>
</students>
